FROM composer

RUN apk --no-cache add rsync

ENV PATH "/tmp/vendor/bin:$PATH"
ENV COMPOSER_HOME /tmp

ENV SURF_VERSION 2.0.0-beta7

COPY ssh_config /etc/ssh/ssh_config

RUN composer global config minimum-stability beta \
    && composer global require typo3/surf:${SURF_VERSION} \
    && composer clear-cache

COPY docker-entrypoint.sh /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]

RUN apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/v3.7/main \
                       --repository http://dl-cdn.alpinelinux.org/alpine/v3.7/community \
                       'nodejs>8.9' \
                       'nodejs-npm>8.9' \
                       'yarn>1.3'

RUN npm install gulp-cli -g \
    && touch ~/.dummy \
    && npm cache clean --force \
    && rm -f ~/.dummy

CMD ["surf"]
