name: Update Docker Hub description
on:
  push:
    branches:
    - main
    paths:
    - README.md
    - .github/workflows/dockerhub-description.yml

jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: t3easy/surf
    steps:
    - uses: actions/checkout@v3

    - name: Docker Hub description
      uses: peter-evans/dockerhub-description@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: ${{ env.IMAGE_NAME }}
        short-description: ${{ github.event.repository.description }}
        enable-url-completion: true